#ifndef CRAZYPOD_UI_METRICS_H
#define CRAZYPOD_UI_METRICS_H

#include "config.h"

#include "lcd.h"

/*
 * Where the furniture goes.
 *
 * The product UI was drawn on a 320x240 canvas with a list down the left and
 * a preview beside it. The Mini's panel is 138x110 at about the same pixel
 * pitch: a little over a sixth of the area, and no room at all for two
 * columns. These are the numbers for both, kept together so the two layouts
 * can be read against each other rather than found one constant at a time.
 *
 * The compact column is not the full one scaled. A list row is as tall as
 * the type it holds plus somewhere to put it, and type stops scaling before
 * a screen does -- so the row heights come from the faces the compact ladder
 * resolves to, and everything else is fitted around them.
 */

#ifdef HAVE_CRAZYPOD_COMPACT_UI

/* Status bar: one line of 8px type with a battery beside it. */
#define CRAZYPOD_METRIC_STATUS_HEIGHT 12

/*
 * The list takes the whole width. There is no preview: a cover at this size
 * would be a smudge, and the room it wants is the room the titles need.
 */
#define CRAZYPOD_METRIC_MENU_PANEL_WIDTH LCD_WIDTH

#define CRAZYPOD_METRIC_MENU_HEADER_X 4
#define CRAZYPOD_METRIC_MENU_HEADER_Y 13
#define CRAZYPOD_METRIC_MENU_HEADER_WIDTH (LCD_WIDTH - 8)
#define CRAZYPOD_METRIC_MENU_HEADER_HEIGHT 12

/*
 * Six rows of fourteen fill what is left exactly. Fourteen is the line box
 * of the 9px face the row titles resolve to, which is the smallest size
 * that is still read rather than guessed at on this panel.
 */
#define CRAZYPOD_METRIC_MENU_ROWS 6
#define CRAZYPOD_METRIC_MENU_ROW_X 0
#define CRAZYPOD_METRIC_MENU_ROW_Y 26
#define CRAZYPOD_METRIC_MENU_ROW_WIDTH (LCD_WIDTH - 4)
#define CRAZYPOD_METRIC_MENU_ROW_HEIGHT 14
#define CRAZYPOD_METRIC_MENU_ROW_STEP 14
/* A rounded selection bar loses two pixels of its own height to the corner
 * at this size, and the corner is not visible anyway. */
#define CRAZYPOD_METRIC_MENU_ROW_RADIUS 0

#define CRAZYPOD_METRIC_MENU_SCROLL_X (LCD_WIDTH - 3)
#define CRAZYPOD_METRIC_MENU_SCROLL_Y 27
#define CRAZYPOD_METRIC_MENU_SCROLL_HEIGHT 82

/* The icon is drawn at its own size, with no disc behind it: a 21px disc
 * around a 14px glyph is most of a row here, and reads as a blob. */
#define CRAZYPOD_METRIC_ROW_ICON_DISC 0
#define CRAZYPOD_METRIC_ROW_ICON_X 2
#define CRAZYPOD_METRIC_ROW_ICON_SIZE 14
#define CRAZYPOD_METRIC_ROW_TEXT_X_WITH_ICON 18
#define CRAZYPOD_METRIC_ROW_TEXT_X 4
#define CRAZYPOD_METRIC_ROW_MARKER_X (CRAZYPOD_METRIC_MENU_ROW_WIDTH - 10)

/* The type the list is set in, as the size a 320x240 screen would ask for;
 * the compact ladder resolves these to 9px and 8px. */
#define CRAZYPOD_METRIC_ROW_TEXT_SIZE 12
#define CRAZYPOD_METRIC_HEADER_TEXT_SIZE 10

/*
 * The watch faces. On the large canvas the dial sits on the left of a wide
 * card with the time and date in a column beside it; there is no room for
 * two columns here, so the dial is centred and the readout goes under it.
 */
#define CRAZYPOD_METRIC_FACE_PANEL_X 2
#define CRAZYPOD_METRIC_FACE_PANEL_Y 14
#define CRAZYPOD_METRIC_FACE_PANEL_WIDTH (LCD_WIDTH - 4)
#define CRAZYPOD_METRIC_FACE_PANEL_HEIGHT (LCD_HEIGHT - 16)
#define CRAZYPOD_METRIC_FACE_PANEL_RADIUS 4
#define CRAZYPOD_METRIC_FACE_DIAL_SIZE 56
#define CRAZYPOD_METRIC_FACE_DIAL_X \
    ((CRAZYPOD_METRIC_FACE_PANEL_WIDTH - CRAZYPOD_METRIC_FACE_DIAL_SIZE) / 2)
#define CRAZYPOD_METRIC_FACE_DIAL_Y 3
/* The column under the dial: caption, the time itself, then the date. */
#define CRAZYPOD_METRIC_FACE_TEXT_X 0
#define CRAZYPOD_METRIC_FACE_TEXT_WIDTH CRAZYPOD_METRIC_FACE_PANEL_WIDTH
#define CRAZYPOD_METRIC_FACE_TIME_Y 62
#define CRAZYPOD_METRIC_FACE_TIME_SIZE 16
#define CRAZYPOD_METRIC_FACE_DETAIL_Y 80
#define CRAZYPOD_METRIC_FACE_DETAIL_SIZE 10

/*
 * The month grid. Seven columns of nineteen fill 133 of the 138, and six
 * rows of twelve leave room for the month and the weekday header above
 * them. The large canvas has columns twice this wide and a caption line
 * the small one drops.
 */
#define CRAZYPOD_METRIC_CAL_PANEL_X 1
#define CRAZYPOD_METRIC_CAL_PANEL_Y 13
#define CRAZYPOD_METRIC_CAL_PANEL_WIDTH (LCD_WIDTH - 2)
#define CRAZYPOD_METRIC_CAL_PANEL_HEIGHT (LCD_HEIGHT - 15)
#define CRAZYPOD_METRIC_CAL_PANEL_RADIUS 3
#define CRAZYPOD_METRIC_CAL_SHOW_CAPTION 0
#define CRAZYPOD_METRIC_CAL_TITLE_X 3
#define CRAZYPOD_METRIC_CAL_TITLE_Y 1
#define CRAZYPOD_METRIC_CAL_TITLE_SIZE 12
#define CRAZYPOD_METRIC_CAL_DAY_LABEL_X 70
#define CRAZYPOD_METRIC_CAL_DAY_LABEL_Y 2
#define CRAZYPOD_METRIC_CAL_DAY_LABEL_WIDTH 62
#define CRAZYPOD_METRIC_CAL_RULE_X 2
#define CRAZYPOD_METRIC_CAL_RULE_Y 15
#define CRAZYPOD_METRIC_CAL_RULE_WIDTH (CRAZYPOD_METRIC_CAL_PANEL_WIDTH - 4)
#define CRAZYPOD_METRIC_CAL_WEEKDAY_Y 17
#define CRAZYPOD_METRIC_CAL_GRID_X 1
#define CRAZYPOD_METRIC_CAL_GRID_Y 26
#define CRAZYPOD_METRIC_CAL_CELL_WIDTH 19
#define CRAZYPOD_METRIC_CAL_CELL_HEIGHT 12
#define CRAZYPOD_METRIC_CAL_DAY_SIZE 10
#define CRAZYPOD_METRIC_CAL_DOT 2

/*
 * The workout screens. The large canvas puts the ring on the left with the
 * elapsed time in a column beside it; here the ring goes on top and the
 * readout under it, as on the watch faces.
 */
#define CRAZYPOD_METRIC_WORKOUT_PANEL_X 2
#define CRAZYPOD_METRIC_WORKOUT_PANEL_Y 14
#define CRAZYPOD_METRIC_WORKOUT_PANEL_WIDTH (LCD_WIDTH - 4)
#define CRAZYPOD_METRIC_WORKOUT_PANEL_HEIGHT (LCD_HEIGHT - 16)
#define CRAZYPOD_METRIC_WORKOUT_PANEL_RADIUS 4
#define CRAZYPOD_METRIC_WORKOUT_TEXT_X 2
#define CRAZYPOD_METRIC_WORKOUT_TEXT_WIDTH (LCD_WIDTH - 8)
#define CRAZYPOD_METRIC_WORKOUT_TITLE_Y 6
#define CRAZYPOD_METRIC_WORKOUT_TITLE_SIZE 12
#define CRAZYPOD_METRIC_WORKOUT_STATE_Y 24
#define CRAZYPOD_METRIC_WORKOUT_STATE_SIZE 16
#define CRAZYPOD_METRIC_WORKOUT_NOTE_Y 48
#define CRAZYPOD_METRIC_WORKOUT_HINT_Y 74
#define CRAZYPOD_METRIC_WORKOUT_NOTE_SIZE 10
#define CRAZYPOD_METRIC_WORKOUT_RING_SIZE 44
#define CRAZYPOD_METRIC_WORKOUT_RING_X ((LCD_WIDTH - 44) / 2)
#define CRAZYPOD_METRIC_WORKOUT_RING_Y 16
#define CRAZYPOD_METRIC_WORKOUT_RING_BORDER 3
#define CRAZYPOD_METRIC_WORKOUT_ACTIVITY_Y 62
#define CRAZYPOD_METRIC_WORKOUT_ELAPSED_Y 74
#define CRAZYPOD_METRIC_WORKOUT_ELAPSED_SIZE 16
#define CRAZYPOD_METRIC_WORKOUT_STATUS_Y 94
#define CRAZYPOD_METRIC_WORKOUT_SHOW_LEGEND 0

#else /* the 320x240 canvas the product UI was drawn on */

#define CRAZYPOD_METRIC_STATUS_HEIGHT 32

#define CRAZYPOD_METRIC_MENU_PANEL_WIDTH 160

#define CRAZYPOD_METRIC_MENU_HEADER_X 16
#define CRAZYPOD_METRIC_MENU_HEADER_Y 38
#define CRAZYPOD_METRIC_MENU_HEADER_WIDTH 128
#define CRAZYPOD_METRIC_MENU_HEADER_HEIGHT 24

#define CRAZYPOD_METRIC_MENU_ROWS 6
#define CRAZYPOD_METRIC_MENU_ROW_X 8
#define CRAZYPOD_METRIC_MENU_ROW_Y 64
#define CRAZYPOD_METRIC_MENU_ROW_WIDTH 140
#define CRAZYPOD_METRIC_MENU_ROW_HEIGHT 28
#define CRAZYPOD_METRIC_MENU_ROW_STEP 28
#define CRAZYPOD_METRIC_MENU_ROW_RADIUS 8

#define CRAZYPOD_METRIC_FACE_PANEL_X 10
#define CRAZYPOD_METRIC_FACE_PANEL_Y 40
#define CRAZYPOD_METRIC_FACE_PANEL_WIDTH 300
#define CRAZYPOD_METRIC_FACE_PANEL_HEIGHT 188
#define CRAZYPOD_METRIC_FACE_PANEL_RADIUS 12
#define CRAZYPOD_METRIC_FACE_DIAL_SIZE 140
#define CRAZYPOD_METRIC_FACE_DIAL_X 14
#define CRAZYPOD_METRIC_FACE_DIAL_Y 23
#define CRAZYPOD_METRIC_FACE_TEXT_X 170
#define CRAZYPOD_METRIC_FACE_TEXT_WIDTH 130
#define CRAZYPOD_METRIC_FACE_TIME_Y 53
#define CRAZYPOD_METRIC_FACE_TIME_SIZE 24
#define CRAZYPOD_METRIC_FACE_DETAIL_Y 97
#define CRAZYPOD_METRIC_FACE_DETAIL_SIZE 10

#define CRAZYPOD_METRIC_CAL_PANEL_X 10
#define CRAZYPOD_METRIC_CAL_PANEL_Y 38
#define CRAZYPOD_METRIC_CAL_PANEL_WIDTH 300
#define CRAZYPOD_METRIC_CAL_PANEL_HEIGHT 194
#define CRAZYPOD_METRIC_CAL_PANEL_RADIUS 12
#define CRAZYPOD_METRIC_CAL_SHOW_CAPTION 1
#define CRAZYPOD_METRIC_CAL_TITLE_X 14
#define CRAZYPOD_METRIC_CAL_TITLE_Y 22
#define CRAZYPOD_METRIC_CAL_TITLE_SIZE 16
#define CRAZYPOD_METRIC_CAL_DAY_LABEL_X 210
#define CRAZYPOD_METRIC_CAL_DAY_LABEL_Y 24
#define CRAZYPOD_METRIC_CAL_DAY_LABEL_WIDTH 72
#define CRAZYPOD_METRIC_CAL_RULE_X 12
#define CRAZYPOD_METRIC_CAL_RULE_Y 50
#define CRAZYPOD_METRIC_CAL_RULE_WIDTH 276
#define CRAZYPOD_METRIC_CAL_WEEKDAY_Y 58
#define CRAZYPOD_METRIC_CAL_GRID_X 10
#define CRAZYPOD_METRIC_CAL_GRID_Y 75
#define CRAZYPOD_METRIC_CAL_CELL_WIDTH 40
#define CRAZYPOD_METRIC_CAL_CELL_HEIGHT 19
#define CRAZYPOD_METRIC_CAL_DAY_SIZE 10
#define CRAZYPOD_METRIC_CAL_DOT 3

#define CRAZYPOD_METRIC_WORKOUT_PANEL_X 18
#define CRAZYPOD_METRIC_WORKOUT_PANEL_Y 48
#define CRAZYPOD_METRIC_WORKOUT_PANEL_WIDTH 284
#define CRAZYPOD_METRIC_WORKOUT_PANEL_HEIGHT 166
#define CRAZYPOD_METRIC_WORKOUT_PANEL_RADIUS 18
#define CRAZYPOD_METRIC_WORKOUT_TEXT_X 18
#define CRAZYPOD_METRIC_WORKOUT_TEXT_WIDTH 248
#define CRAZYPOD_METRIC_WORKOUT_TITLE_Y 20
#define CRAZYPOD_METRIC_WORKOUT_TITLE_SIZE 16
#define CRAZYPOD_METRIC_WORKOUT_STATE_Y 57
#define CRAZYPOD_METRIC_WORKOUT_STATE_SIZE 24
#define CRAZYPOD_METRIC_WORKOUT_NOTE_Y 96
#define CRAZYPOD_METRIC_WORKOUT_HINT_Y 140
#define CRAZYPOD_METRIC_WORKOUT_NOTE_SIZE 10
#define CRAZYPOD_METRIC_WORKOUT_RING_SIZE 126
#define CRAZYPOD_METRIC_WORKOUT_RING_X 26
#define CRAZYPOD_METRIC_WORKOUT_RING_Y 49
#define CRAZYPOD_METRIC_WORKOUT_RING_BORDER 5
#define CRAZYPOD_METRIC_WORKOUT_ACTIVITY_Y 56
#define CRAZYPOD_METRIC_WORKOUT_ELAPSED_Y 76
#define CRAZYPOD_METRIC_WORKOUT_ELAPSED_SIZE 24
#define CRAZYPOD_METRIC_WORKOUT_STATUS_Y 119
#define CRAZYPOD_METRIC_WORKOUT_SHOW_LEGEND 1

#define CRAZYPOD_METRIC_MENU_SCROLL_X 153
#define CRAZYPOD_METRIC_MENU_SCROLL_Y 66
#define CRAZYPOD_METRIC_MENU_SCROLL_HEIGHT 164

#define CRAZYPOD_METRIC_ROW_ICON_DISC 1
#define CRAZYPOD_METRIC_ROW_ICON_X 6
#define CRAZYPOD_METRIC_ROW_ICON_SIZE 21
#define CRAZYPOD_METRIC_ROW_TEXT_X_WITH_ICON 34
#define CRAZYPOD_METRIC_ROW_TEXT_X 12
#define CRAZYPOD_METRIC_ROW_MARKER_X 128

#define CRAZYPOD_METRIC_ROW_TEXT_SIZE 18
#define CRAZYPOD_METRIC_HEADER_TEXT_SIZE 15

#endif

#define CRAZYPOD_METRIC_MENU_PANEL_Y CRAZYPOD_METRIC_STATUS_HEIGHT
#define CRAZYPOD_METRIC_MENU_PANEL_HEIGHT \
    (LCD_HEIGHT - CRAZYPOD_METRIC_MENU_PANEL_Y)

/* What is left beside the list, if anything. Zero means there is no room
 * for a preview and the screens that would draw one must not. */
#define CRAZYPOD_METRIC_PREVIEW_X CRAZYPOD_METRIC_MENU_PANEL_WIDTH
#define CRAZYPOD_METRIC_PREVIEW_WIDTH \
    (LCD_WIDTH - CRAZYPOD_METRIC_MENU_PANEL_WIDTH)

#endif
